### ISSUE TITLE
Cannot run the app on Android

### ISSUE THREAD

**Issue by PaulSec** [skotturi/places-demo#1]
Hi, 

I installed the GeoLocation plugin using `ionic plugin add org.apache.cordova.geolocation`, built the application and ran it on an Android device. Impossible to make it work (the GPS is on). 

The app works perfectly in the web browser though. Have you had that kind of issue? 

Great project anyway, cheers!

**Comment by danidano** [comment]
Hi PaulSec,

Did you try to remove and install android platform ?

**Comment by santekotturi** [comment]
@PaulSec I echo what @danidano said, removing and then adding the android (or iOS) platforms forces each platforms config files to link up all the necessary cordova plugins. 

```
ionic platform remove android
ionic platform add android
```

(replace android with iOS if you're having issues with iOS)

should do the trick. 
Glad you find it useful!!

**Comment by PaulSec** [comment]
Just tried it right now and it works fine!

Cheers,

**Comment by santekotturi** [comment]
Awesome, glad it's working. I'm not sure if newer version of the ionic CLI handle this better, I seem to run into this less and less but it used to be a really frustrating (and not really documented) issue a lot of us were having with adding cordova plugins to Ionic apps.
